# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'upPhoiWindowLDeFaj.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_UpPhoiWindow(object):
    def setupUi(self, UpPhoiWindow):
        if not UpPhoiWindow.objectName():
            UpPhoiWindow.setObjectName(u"UpPhoiWindow")
        UpPhoiWindow.resize(1377, 789)
        UpPhoiWindow.setStyleSheet(u"background-color: #040f13;")
        self.centralwidget = QWidget(UpPhoiWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(16777215, 1000))
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(1252, 0))
        self.frame.setMaximumSize(QSize(16777215, 450))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(31, 31, 31);")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 0, 71, 16))
        self.pushButton = QPushButton(self.frame_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(560, 400, 101, 31))
        self.pushButton.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.textEdit = QTextEdit(self.frame_3)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(70, 400, 461, 31))
        self.textEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.image_label = QLabel(self.frame_3)
        self.image_label.setObjectName(u"image_label")
        self.image_label.setGeometry(QRect(50, 20, 591, 361))

        self.horizontalLayout.addWidget(self.frame_3)

        self.frame_4 = QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setStyleSheet(u"\n"
"background-color: rgb(31, 31, 31);")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 0, 111, 16))
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_img = QLabel(self.frame_4)
        self.label_img.setObjectName(u"label_img")
        self.label_img.setGeometry(QRect(40, 20, 591, 361))
        self.label_36 = QLabel(self.frame_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(520, 410, 151, 20))
        self.label_36.setStyleSheet(u"\n"
"color: rgb(0, 85, 255);\n"
"text-decoration: underline;")
        self.btn_preview = QPushButton(self.frame_4)
        self.btn_preview.setObjectName(u"btn_preview")
        self.btn_preview.setGeometry(QRect(20, 400, 101, 31))
        self.btn_preview.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")

        self.horizontalLayout.addWidget(self.frame_4)


        self.verticalLayout.addWidget(self.frame)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(0, 300))
        self.frame_2.setMaximumSize(QSize(16777215, 300))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.frame_5 = QFrame(self.frame_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.label_15 = QLabel(self.frame_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 10, 361, 21))
        self.label_15.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.frame_5)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 120, 21, 21))
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_17 = QLabel(self.frame_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 160, 71, 21))
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_18 = QLabel(self.frame_5)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 200, 71, 21))
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_19 = QLabel(self.frame_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 240, 51, 21))
        self.label_19.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_20 = QLabel(self.frame_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 80, 31, 21))
        self.label_20.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_21 = QLabel(self.frame_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(270, 200, 20, 21))
        self.label_21.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_11 = QSpinBox(self.frame_5)
        self.spinBox_11.setObjectName(u"spinBox_11")
        self.spinBox_11.setGeometry(QRect(190, 190, 61, 31))
        self.spinBox_11.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_11.setMaximum(9999999)
        self.spinBox_12 = QSpinBox(self.frame_5)
        self.spinBox_12.setObjectName(u"spinBox_12")
        self.spinBox_12.setGeometry(QRect(80, 190, 61, 31))
        self.spinBox_12.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_12.setMaximum(9999999)
        self.spinBox_13 = QSpinBox(self.frame_5)
        self.spinBox_13.setObjectName(u"spinBox_13")
        self.spinBox_13.setGeometry(QRect(300, 190, 61, 31))
        self.spinBox_13.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_13.setMinimum(-360)
        self.spinBox_13.setMaximum(360)
        self.label_22 = QLabel(self.frame_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(160, 200, 20, 21))
        self.label_22.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_23 = QLabel(self.frame_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(270, 120, 20, 21))
        self.label_23.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_14 = QSpinBox(self.frame_5)
        self.spinBox_14.setObjectName(u"spinBox_14")
        self.spinBox_14.setGeometry(QRect(190, 110, 61, 31))
        self.spinBox_14.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_14.setMaximum(9999999)
        self.spinBox_15 = QSpinBox(self.frame_5)
        self.spinBox_15.setObjectName(u"spinBox_15")
        self.spinBox_15.setGeometry(QRect(80, 110, 61, 31))
        self.spinBox_15.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_15.setMaximum(9999999)
        self.spinBox_16 = QSpinBox(self.frame_5)
        self.spinBox_16.setObjectName(u"spinBox_16")
        self.spinBox_16.setGeometry(QRect(300, 110, 61, 31))
        self.spinBox_16.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_16.setMinimum(-360)
        self.spinBox_16.setMaximum(360)
        self.label_24 = QLabel(self.frame_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(160, 120, 20, 21))
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_25 = QLabel(self.frame_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(270, 160, 20, 21))
        self.label_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_17 = QSpinBox(self.frame_5)
        self.spinBox_17.setObjectName(u"spinBox_17")
        self.spinBox_17.setGeometry(QRect(190, 150, 61, 31))
        self.spinBox_17.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_17.setMaximum(9999999)
        self.spinBox_18 = QSpinBox(self.frame_5)
        self.spinBox_18.setObjectName(u"spinBox_18")
        self.spinBox_18.setGeometry(QRect(80, 150, 61, 31))
        self.spinBox_18.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_18.setMaximum(9999999)
        self.spinBox_19 = QSpinBox(self.frame_5)
        self.spinBox_19.setObjectName(u"spinBox_19")
        self.spinBox_19.setGeometry(QRect(300, 150, 61, 31))
        self.spinBox_19.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_19.setMinimum(-360)
        self.spinBox_19.setMaximum(360)
        self.label_26 = QLabel(self.frame_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(160, 160, 20, 21))
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_27 = QLabel(self.frame_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(270, 240, 20, 21))
        self.label_27.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_20 = QSpinBox(self.frame_5)
        self.spinBox_20.setObjectName(u"spinBox_20")
        self.spinBox_20.setGeometry(QRect(190, 230, 61, 31))
        self.spinBox_20.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_20.setMaximum(9999999)
        self.spinBox_21 = QSpinBox(self.frame_5)
        self.spinBox_21.setObjectName(u"spinBox_21")
        self.spinBox_21.setGeometry(QRect(80, 230, 61, 31))
        self.spinBox_21.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_21.setMaximum(9999999)
        self.spinBox_22 = QSpinBox(self.frame_5)
        self.spinBox_22.setObjectName(u"spinBox_22")
        self.spinBox_22.setGeometry(QRect(300, 230, 61, 31))
        self.spinBox_22.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_22.setMinimum(-360)
        self.spinBox_22.setMaximum(360)
        self.label_28 = QLabel(self.frame_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(160, 240, 20, 21))
        self.label_28.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_23 = QSpinBox(self.frame_5)
        self.spinBox_23.setObjectName(u"spinBox_23")
        self.spinBox_23.setGeometry(QRect(80, 70, 61, 31))
        self.spinBox_23.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_23.setMaximum(9999999)
        self.label_29 = QLabel(self.frame_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(160, 80, 20, 21))
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_24 = QSpinBox(self.frame_5)
        self.spinBox_24.setObjectName(u"spinBox_24")
        self.spinBox_24.setGeometry(QRect(300, 70, 61, 31))
        self.spinBox_24.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_24.setMinimum(-360)
        self.spinBox_24.setMaximum(360)
        self.spinBox_25 = QSpinBox(self.frame_5)
        self.spinBox_25.setObjectName(u"spinBox_25")
        self.spinBox_25.setGeometry(QRect(190, 70, 61, 31))
        self.spinBox_25.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_25.setMaximum(9999999)
        self.label_30 = QLabel(self.frame_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(270, 80, 20, 21))
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout_2.addWidget(self.frame_5)

        self.frame_7 = QFrame(self.frame_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame_8 = QFrame(self.frame_7)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setStyleSheet(u"")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_32 = QLabel(self.frame_8)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 90, 81, 16))
        self.label_32.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_33 = QLabel(self.frame_8)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 130, 81, 16))
        self.label_33.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_34 = QLabel(self.frame_8)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 170, 61, 16))
        self.label_34.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_35 = QLabel(self.frame_8)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 210, 81, 16))
        self.label_35.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.comboBox_2 = QComboBox(self.frame_8)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 80, 291, 31))
        self.comboBox_2.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_3 = QComboBox(self.frame_8)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(90, 120, 191, 31))
        self.comboBox_3.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_4 = QComboBox(self.frame_8)
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(290, 120, 91, 31))
        self.comboBox_4.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_5 = QComboBox(self.frame_8)
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(90, 160, 291, 31))
        self.comboBox_5.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_6 = QComboBox(self.frame_8)
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(90, 200, 291, 31))
        self.comboBox_6.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.comboBox = QComboBox(self.frame_8)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(90, 30, 291, 31))
        self.comboBox.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.label_31 = QLabel(self.frame_8)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, -10, 81, 31))
        self.label_31.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout_2.addWidget(self.frame_8)


        self.horizontalLayout_2.addWidget(self.frame_7)

        self.frame_6 = QFrame(self.frame_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_6)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 60, 111, 21))
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.frame_6)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 100, 131, 21))
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6 = QLabel(self.frame_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 180, 111, 21))
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_7 = QLabel(self.frame_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 220, 131, 21))
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.frame_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(210, 60, 57, 15))
        self.label_9 = QLabel(self.frame_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(300, 70, 20, 21))
        self.label_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.frame_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(240, 110, 20, 21))
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.frame_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(350, 110, 20, 21))
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox = QSpinBox(self.frame_6)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(160, 60, 121, 31))
        self.spinBox.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox.setMaximum(99999999)
        self.spinBox_2 = QSpinBox(self.frame_6)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(330, 60, 111, 31))
        self.spinBox_2.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_2.setMaximum(999999)
        self.spinBox_3 = QSpinBox(self.frame_6)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(160, 100, 61, 31))
        self.spinBox_3.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_3.setMaximum(999999)
        self.spinBox_4 = QSpinBox(self.frame_6)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(270, 100, 61, 31))
        self.spinBox_4.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_4.setMaximum(999999)
        self.spinBox_5 = QSpinBox(self.frame_6)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(380, 100, 61, 31))
        self.spinBox_5.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_5.setMinimum(-360)
        self.spinBox_5.setMaximum(360)
        self.spinBox_6 = QSpinBox(self.frame_6)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(380, 210, 61, 31))
        self.spinBox_6.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_6.setMinimum(-360)
        self.spinBox_6.setMaximum(999999)
        self.spinBox_7 = QSpinBox(self.frame_6)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(160, 210, 61, 31))
        self.spinBox_7.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_7.setMaximum(999999)
        self.spinBox_8 = QSpinBox(self.frame_6)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(330, 170, 111, 31))
        self.spinBox_8.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_8.setMaximum(999999)
        self.spinBox_9 = QSpinBox(self.frame_6)
        self.spinBox_9.setObjectName(u"spinBox_9")
        self.spinBox_9.setGeometry(QRect(270, 210, 61, 31))
        self.spinBox_9.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_9.setMaximum(99999999)
        self.spinBox_10 = QSpinBox(self.frame_6)
        self.spinBox_10.setObjectName(u"spinBox_10")
        self.spinBox_10.setGeometry(QRect(160, 170, 121, 31))
        self.spinBox_10.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_10.setMaximum(99999999)
        self.label_12 = QLabel(self.frame_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(240, 220, 20, 21))
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_13 = QLabel(self.frame_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(350, 220, 20, 21))
        self.label_13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_14 = QLabel(self.frame_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(300, 180, 20, 21))
        self.label_14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.frame_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 171, 16))
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout_2.addWidget(self.frame_6)


        self.verticalLayout.addWidget(self.frame_2)

        UpPhoiWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpPhoiWindow)

        QMetaObject.connectSlotsByName(UpPhoiWindow)
    # setupUi

    def retranslateUi(self, UpPhoiWindow):
        UpPhoiWindow.setWindowTitle(QCoreApplication.translate("UpPhoiWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("UpPhoiWindow", u"Ph\u00f4i g\u1ed1c", None))
        self.pushButton.setText(QCoreApplication.translate("UpPhoiWindow", u"Browse", None))
        self.image_label.setText("")
        self.label_2.setText(QCoreApplication.translate("UpPhoiWindow", u"Ph\u00f4i ch\u1ec9nh s\u1eeda", None))
        self.label_img.setText("")
        self.label_36.setText(QCoreApplication.translate("UpPhoiWindow", u"Video h\u01b0\u1edbng d\u1eabn", None))
        self.btn_preview.setText(QCoreApplication.translate("UpPhoiWindow", u"Preview", None))
        self.label_15.setText(QCoreApplication.translate("UpPhoiWindow", u"V\u1ecb tr\u00ed[CHI\u1ec0U NGANG X CHI\u1ec0U D\u1eccC X XOAY CHI\u1ec0U]", None))
        self.label_16.setText(QCoreApplication.translate("UpPhoiWindow", u"H\u1ecd ", None))
        self.label_17.setText(QCoreApplication.translate("UpPhoiWindow", u"Ng\u00e0y sinh", None))
        self.label_18.setText(QCoreApplication.translate("UpPhoiWindow", u"Gi\u1edbi t\u00ednh", None))
        self.label_19.setText(QCoreApplication.translate("UpPhoiWindow", u"\u0110\u1ecba ch\u1ec9", None))
        self.label_20.setText(QCoreApplication.translate("UpPhoiWindow", u"T\u00ean", None))
        self.label_21.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_22.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_23.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_24.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_25.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_26.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_27.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_28.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_29.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_30.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_32.setText(QCoreApplication.translate("UpPhoiWindow", u"K\u00edch c\u1ee1 ch\u1eef", None))
        self.label_33.setText(QCoreApplication.translate("UpPhoiWindow", u"Ki\u1ec3u ch\u1eef", None))
        self.label_34.setText(QCoreApplication.translate("UpPhoiWindow", u"M\u00e0u ch\u1eef", None))
        self.label_35.setText(QCoreApplication.translate("UpPhoiWindow", u"Ng\u00f4n ng\u1eef", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("UpPhoiWindow", u"Ch\u1eef \u0111\u1eadm", None))

        self.comboBox_5.setItemText(0, QCoreApplication.translate("UpPhoiWindow", u"\u0110en", None))

        self.comboBox_6.setItemText(0, QCoreApplication.translate("UpPhoiWindow", u"Ti\u1ebfng Anh", None))

        self.comboBox.setItemText(0, QCoreApplication.translate("UpPhoiWindow", u"T\u00e1ch ri\u00eang h\u1ecd, t\u00ean", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("UpPhoiWindow", u"H\u1ecd t\u00ean \u0111\u1ea7y \u0111\u1ee7", None))

        self.label_31.setText(QCoreApplication.translate("UpPhoiWindow", u"Thi\u1ebft l\u1eadp", None))
        self.label_4.setText(QCoreApplication.translate("UpPhoiWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh 1", None))
        self.label_5.setText(QCoreApplication.translate("UpPhoiWindow", u"V\u1ecb tr\u00ed \u0111\u1eb7t v\u00e0o ph\u00f4i", None))
        self.label_6.setText(QCoreApplication.translate("UpPhoiWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh 2", None))
        self.label_7.setText(QCoreApplication.translate("UpPhoiWindow", u"V\u1ecb tr\u00ed \u0111\u1eb7t v\u00e0o ph\u00f4i", None))
        self.label_8.setText(QCoreApplication.translate("UpPhoiWindow", u"TextLabel", None))
        self.label_9.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_10.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_11.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_12.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_13.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_14.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_3.setText(QCoreApplication.translate("UpPhoiWindow", u"Thi\u1ebft l\u1eadp \u1ea3nh ph\u00f4i", None))
    # retranslateUi

